{
    album = [
        {
            idAlbum: "2115888",
            idArtist: "112024",
            idLabel: "47129",
            strAlbum: "Echoes of Silence",
            strAlbumStripped: "Echoes of Silence",
            strArtist: "The Weeknd",
            strArtistStripped: "The Weeknd",
            intYearReleased: "2011",
            strStyle: "Urban/R&B",
            strGenre: "R&B",
            strLabel: "Republic Records",
            strReleaseFormat: "Album",
            intSales: "0",
            strAlbumThumb:
                "https://www.theaudiodb.com/images/media/album/thumb/xwvwvp1342551819.jpg",
            strAlbumThumbHQ: null,
            strAlbumThumbBack: null,
            strAlbumCDart: null,
            strAlbumSpine: null,
            strAlbum3DCase: null,
            strAlbum3DFlat: null,
            strAlbum3DFace: null,
            strAlbum3DThumb: null,
            strDescriptionEN:
                'Echoes of Silence is the third mixtape by Canadian artist, The Weeknd, released December 21, 2011 via his official website. The release follows his Polaris Music Prize-nominated debut release House of Balloons and his second album Thursday, both released earlier the same year. The project is the final installment in the trilogy of free albums released by The Weeknd in 2011.\nThe album was preceded by the release of the single, "Initiation". Long-time collaborator Carlo "Illangelo" Montagnese returned to produce the bulk of the project, with other production contributions coming from Clams Casino and DropxLife of the XO crew. Rapper Juicy J contributes a short spoken-word interlude at the end of "Same Old Song".\nEchoes of Silence received general acclaim from music critics. At Metacritic, which assigns a normalized rating out of 100 to reviews from mainstream critics and fans, the album received an average score of 82, based on 16 reviews, which indicates "universal acclaim".\nThe album was named as a longlisted nominee for the 2012 Polaris Music Prize on June 14, 2012. This marks the second consecutive year The Weeknd has been nominated for the award.[14]',
            strDescriptionDE: null,
            strDescriptionFR: null,
            strDescriptionCN: null,
            strDescriptionIT: null,
            strDescriptionJP: null,
            strDescriptionRU: null,
            strDescriptionES: null,
            strDescriptionPT: null,
            strDescriptionSE: null,
            strDescriptionNL: null,
            strDescriptionHU: null,
            strDescriptionNO: null,
            strDescriptionIL: null,
            strDescriptionPL: null,
            intLoved: null,
            intScore: "8.5",
            intScoreVotes: "2",
            strReview: "",
            strMood: "Intense",
            strTheme: null,
            strSpeed: null,
            strLocation: null,
            strMusicBrainzID: "72087170-41c6-4371-a87c-47061feeda10",
            strMusicBrainzArtistID: "c8b03190-306c-4120-bb0b-6f2ebfc06ea9",
            strAllMusicID: null,
            strBBCReviewID: null,
            strRateYourMusicID: null,
            strDiscogsID: "399750",
            strWikidataID: null,
            strWikipediaID: null,
            strGeniusID: "Echoes-of-silence",
            strLyricWikiID: null,
            strMusicMozID: null,
            strItunesID: null,
            strAmazonID: null,
            strLocked: "unlocked",
        },
    ];
}
